image: docker:19

stages:
- build dependencies
- build library
- test

variables:
  BOOST_VERSION: 1.75.0

Build Python and Boost:
  stage: build dependencies
  needs: []
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - cd dependencies
    - | 
      if $(docker pull registry.gitlab.com/pep10/libsim/pyboost:${BOOST_VERSION}); then
        echo success
      else
        docker build -t registry.gitlab.com/pep10/libsim/pyboost:${BOOST_VERSION} -f BuildDeps.Dockerfile .
      fi
    - docker push registry.gitlab.com/pep10/libsim/pyboost:${BOOST_VERSION} 
  after_script:
    - docker rmi registry.gitlab.com/pep10/libsim/pyboost:${BOOST_VERSION}


Build Catch:
  stage: build dependencies
  needs: []
  script:
    - echo "Done"

Build Magic Enum:
  stage: build dependencies
  needs: []
  script:
    - echo "Done"

Build library:
  stage: build library
  needs: [Build Catch, Build Magic Enum]
  script:
    - docker build -t ci.${CI_COMMIT_SHORT_SHA} .
  after_script:
    - docker rmi ci.${CI_COMMIT_SHORT_SHA}