image: docker:19

stages:
- build dependencies
- build library
- test

variables:
  BUILD_VERSION: v0.3.0

Build Python and Boost:
  stage: build dependencies
  needs: []
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - cd ./.devcontainer
    - (docker pull registry.gitlab.com/pep10/libsim/pyboost:${BUILD_VERSION} && echo success) || (docker build -t registry.gitlab.com/pep10/libsim/pyboost:$BUILD_VERSION -f . ) 
    - docker push registry.gitlab.com/pep10/libsim/pyboost:$BUILD_VERSION


Build Catch:
  stage: build dependencies
  needs: []
  script:
    - echo "Done"

Build Magic Enum:
  stage: build dependencies
  needs: []
  script:
    - echo "Done"

Build C++ bindings:
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  stage: test
  image: registry.gitlab.com/pep10/libsim/pyboost:${BUILD_VERSION}
  needs: [Build Python and Boost]
  script:
    - source /emsdk/emsdk_env.sh
    - export CXX=/emsdk/llvm/git/build_master_64/bin/clang++
    - export C=/emsdk/llvm/git/build_master_64/bin/clang
    - mkdir build && cd build
    - cmake ../
    - make -j20 && make test

Build emscripten bindings:
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  stage: test
  image: registry.gitlab.com/pep10/libsim/pyboost:${BUILD_VERSION}
  needs: [Build Python and Boost]
  script:
    - source /emsdk/emsdk_env.sh
    - mkdir build && cd build
    - emcmake cmake -DBoost_INCLUDE_DIR=/boost/ ../
    - emmake make -j20
    - node ./test/libisa/test-lib.js
    - npm config set @pep10:registry https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/
    - npm config set '//gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken' ${CI_JOB_TOKEN}